var loadMoreBtnIndex = document.getElementById('load-more-index')
var loadBoxIndex = document.getElementById('load-more-index-conteiner')

//My stuff
var counter = 0;


var textIndex = [
  '<div class=" col-xs-12 col-md-6 all_width  left_ps orng  video_icon" style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/evidence/images/543d27d37353e.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/evidence/6"><span class="view_bl"><span class="view_share"><span class="share_icon">809</span><span class="view_icon">6</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Докази</span></span><span class="text_descr">Воскресіння                      </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  left_ps blue  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/545a1b588302e.jpg" alt="">   </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/chelovek_ili_krolik"><span class="view_bl"><span class="view_share"><span class="share_icon">1</span><span class="view_icon">575</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Людина чі кролик (К.Льюис)                      </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps blue  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464a2b8b49e4.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/dokumenty_nz"><span class="view_bl"><span class="view_share"><span class="share_icon">0</span><span class="view_icon">321</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Документи Нового Заповіта: Чи достовірні вони ? (Ф.Брюс)                      </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps green  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464a265ad954.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/ne_prosto_plotnik"><span class="view_bl"><span class="view_share"><span class="share_icon">0</span><span class="view_icon">376</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Не просто тесля (Д.МакДауэлл)                      </span></span></span></a></div></div>',
  '<div class=" col-xs-12 col-md-6 all_width  left_ps orng  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464bb37aece7.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/neosporimie_svidetelstva"><span class="view_bl"><span class="view_share"><span class="share_icon">0</span><span class="view_icon">529</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Незаперечні свідчення (О.МакДауелл)                      </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  left_ps blue  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/545a2748ec796.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/nobelevskie_laureaty_ob_iisuse"><span class="view_bl"><span class="view_share"><span class="share_icon">2</span><span class="view_icon">991</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Статья</span></span><span class="text_descr">Нобелівські лауреати, філософи і вчені про Ісуса                     </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps blue  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464a22602c78.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/istorichnost_voskreseniya"><span class="view_bl"><span class="view_share"><span class="share_icon">0</span><span class="view_icon">861</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Історичність воскресіння: моральний стрижень (Б.Літтл)                      </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps green  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464a1cf8fd73.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/nekhristiane_o_khriste"><span class="view_bl"><span class="view_share"><span class="share_icon">1</span><span class="view_icon">518</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Статья</span></span><span class="text_descr">Ранні свідчення про Ісуса з нехристиянських джерел (М.Леггорн)                      </span></span></span></a></div></div>',
  '<div class=" col-xs-12 col-md-6 all_width  left_ps orng  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464a13f404a9.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/zlodeianiya_cerkvi"><span class="view_bl"><span class="view_share"><span class="share_icon">0</span><span class="view_icon">640</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">А як щодо злодіянь Церкви? (Дж.Сарфаті)                      </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  left_ps blue  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/54649fecb6847.jpg" alt="">   </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/bogoslovsko-nravstvennaya-problema-teisticheskogo-evvolucionizma"><span class="view_bl"><span class="view_share"><span class="share_icon">0</span><span class="view_icon">532</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Богословсько-моральна проблема теистического еволюціонізму (Священик І.Алферов)                     </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps blue  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464a8d1977b8.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/hristianskaya-demorfologizatsiya"><span class="view_bl"><span class="view_share"><span class="share_icon">28</span><span class="view_icon">894</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Християнська деміфологізація - шлях до науки (Диякон А. Кураєв)                      </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps green  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464aac92b4b3.jpg" alt="">   </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/hristianstvo"><span class="view_bl"><span class="view_share"><span class="share_icon">0</span><span class="view_icon">284</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Християнство (А. Мень)                     </span></span></span></a></div></div>',
  '<div class=" col-xs-12 col-md-6 all_width  left_ps orng  " style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/articles/images/5464a80f0bf1e.jpg" alt="">   </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/articles/chelovek-v-novom-zavete"><span class="view_bl"><span class="view_share"><span class="share_icon">0</span><span class="view_icon">626</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Стаття</span></span><span class="text_descr">Людина в Новому Завіті. Гуманізм і християнство</span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  left_ps blue  video_icon" style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/questions/images/542189955b225.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/questions/5"><span class="view_bl"><span class="view_share"><span class="share_icon">1507</span><span class="view_icon">2</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Запитання</span></span><span class="text_descr">Чи не суперечить віра здоровому глузду? </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps blue  video_icon" style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/questions/images/543ce4b5ad0cf.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/questions/4"><span class="view_bl"><span class="view_share"><span class="share_icon">563</span><span class="view_icon">6</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Запитання</span></span><span class="text_descr">Чи не зарозуміло вважати, що до Бога можна прийти тільки через Ісуса Христа?                    </span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps green  video_icon" style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/questions/images/54218918627d3.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/questions/6"><span class="view_bl"><span class="view_share"><span class="share_icon">360</span><span class="view_icon">7</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Запитання</span></span><span class="text_descr">Навіщо хорошим і порядним людям Христос?                     </span></span></span></a></div></div>',
  '<div class=" col-xs-12 col-md-6 all_width  left_ps orng  video_icon" style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/questions/images/543d4052882a5.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/questions/7"><span class="view_bl"><span class="view_share"><span class="share_icon">490</span><span class="view_icon">4</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Запытання</span></span><span class="text_descr">Чи дійсно воскресіння Христа - історичний факт?</span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  left_ps blue  video_icon" style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/questions/images/543e5dc8499a1.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/questions/2"><span class="view_bl"><span class="view_share"><span class="share_icon">682</span><span class="view_icon">5</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Запитання</span></span><span class="text_descr">Чи не виключає наука існування чудес?</span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps blue  video_icon" style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/questions/images/543e644fb04d6.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/questions/1"><span class="view_bl"><span class="view_share"><span class="share_icon">2157</span><span class="view_icon">1</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Запитання</span></span><span class="text_descr">Достовірність Євангелія від Луки</span></span></span></a></div></div><div class=" col-xs-12 col-md-6 all_width  right_ps green  video_icon" style="display: block; opacity: 1; visibility: visible;"><div class="col-xs-6 img_title"><img src="http://statics.t233.cvcis.org/web//content/questions/images/543e5ed41a5a9.jpg" alt="">    </div><div class="col-xs-6 text_title"><a href="http://otkroy.org/questions/3"><span class="view_bl"><span class="view_share"><span class="share_icon">774</span><span class="view_icon">3</span></span></span><span class="text"><span class="text_fix_bl"><span class="heading"><span>Запитання</span></span><span class="text_descr">Якщо Бог любить і всемогутній, чому люди страждають?</span></span></span></a></div></div>'
]

var clearFunc = function(text){
  var src = document.createElement('div');
  src.innerHTML = ''
  src.innerHTML = text[counter]
  counter++
  return(src)
}

//Index load more press 
loadMoreBtnIndex.onclick = function(){
  if(counter >= textIndex.length){
    loadMoreBtnIndex.style.display = 'none'
  } else {
    loadBoxIndex.appendChild(clearFunc(textIndex))
  }
}



